---
abstract: 'Templates with embedded Perl'
author:
  - 'Maurice Aubrey <maurice.aubrey@gmail.com>'
build_requires:
  File::Temp: '0'
  Scalar::Util: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Forge
requires:
  Carp: '0'
  Encode: '0'
  File::Spec: '0'
  HTML::Entities: '0'
  Method::Alias: '0'
  URI::Escape: '0'
  autodie: '0'
  perl: v5.16.0
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  homepage: https://github.com/mla/text-forge
  repository: https://github.com/mla/text-forge.git
version: '6.01'
