# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Forge
version:      4.01
version_from: lib/Text/Forge.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    File::Spec:                    0
    HTML::Entities:                0
    Test::More:                    0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
